schema_name: smash_dr2
table_name: object
method: service.search  # options: service.search, async, async_delete

# Target type: SMASH field, cluster, coordinates, list of coords
type: list of coords

# Object identifier depending on type:
# - SMASH field: integer 1–247
# - cluster: cluster name to be checked in Bica catalogues or Simbad
# - coordinates: RA DEC in any format accepted by Simbad
# - list of coords: path to file with RA DEC values (e.g. coords_list.txt)
object: coords_list.txt
radius: 0.0833  # in degrees

tabs_path: tables/
cats_path: catalogs/
figs_path: figures/
